# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20161225_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='next_start_at_match_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='execution',
            name='start_at_match_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_seq_num',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='account_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
