# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20161225_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='lobby_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='matchplayer',
            unique_together=set([('player', 'match')]),
        ),
    ]
