# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20161225_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execution',
            old_name='next_start_at_match_id',
            new_name='next_start_at_match_seq_num',
        ),
        migrations.RenameField(
            model_name='execution',
            old_name='start_at_match_id',
            new_name='start_at_match_seq_num',
        ),
        migrations.AlterField(
            model_name='match',
            name='match_seq_num',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
