# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20161225_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='barracks_status_dire',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='barracks_status_radiant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='cluster',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='dire_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='engine',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='first_blood_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='flags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='game_mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='human_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='leagueid',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='negative_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='positive_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='radiant_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='radiant_win',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='tower_status_dire',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='tower_status_radiant',
            field=models.IntegerField(default=0),
        ),
    ]
