# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20161225_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('ability', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('match_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.MatchPlayer')),
            ],
        ),
    ]
