# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_remove_execution_raw_response'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchplayer',
            unique_together=set([]),
        ),
    ]
